#!/bin/bash
cd "$(dirname "$0")"
echo "--- Desktop2Stereo Installer for Mac (for Apple Silicon Chips: M1, M2, M3, M4...) ---"
echo "- Setting up the virtual environment"

# Set paths
VIRTUAL_ENV=".env"
PYTHON_EXE="python3"

# Check if Python is available
if ! command -v $PYTHON_EXE &> /dev/null
then
    echo "Python is not found in PATH. Please install Python 3.11 first."
    read -p "Press enter to exit..."
    exit 1
fi

# Create virtual environment if it doesn't exist
if [ ! -f "./$VIRTUAL_ENV/bin/activate" ]; then
    echo "Creating virtual environment..."
    $PYTHON_EXE -m venv "./$VIRTUAL_ENV"
    if [ $? -ne 0 ]; then
        echo "Failed to create virtual environment"
        read -p "Press enter to exit..."
        exit 1
    fi
fi

# Activate virtual environment
echo "- Virtual environment activation"
source "./$VIRTUAL_ENV/bin/activate"
if [ $? -ne 0 ]; then
    echo "Failed to activate virtual environment"
    read -p "Press enter to exit..."
    exit 1
fi

# Update pip
echo "- Updating the pip package"
$PYTHON_EXE -m pip install --upgrade pip --no-cache-dir --trusted-host http://mirrors.aliyun.com/pypi/simple/
if [ $? -ne 0 ]; then
    echo "Failed to update pip"
    read -p "Press enter to exit..."
    exit 1
fi

# Install requirements
echo
echo "- Installing the requirements"
# check homebrew and install portaudio if not installed
if ! command -v brew &> /dev/null
then
    echo "Homebrew is not found in PATH. Please install Homebrew first from https://brew.sh/"
    read -p "Press enter to exit..."
    exit 1
fi
# check if portaudio is installed
if ! brew list portaudio &> /dev/null
then
    echo "Installing portaudio via Homebrew..."
    brew install portaudio
    if [ $? -ne 0 ]; then
        echo "Failed to install portaudio"
        read -p "Press enter to exit..."
        exit 1
    fi
fi
$PYTHON_EXE -m pip install -r ./requirements-mps.txt --no-cache-dir --trusted-host http://mirrors.aliyun.com/pypi/simple/
$PYTHON_EXE -m pip install -r ./requirements.txt --no-cache-dir --trusted-host http://mirrors.aliyun.com/pypi/simple/
if [ $? -ne 0 ]; then
    echo "Failed to install requirements"
    read -p "Press enter to exit..."
    exit 1
fi

echo "Python environment deployed successfully."
read -p "You can close this terminal window to exit..."
exit
