Capture Mode: Monitor
Monitor Index: 1
Window Title: ''
FPS: 60
Show FPS: false
Output Resolution: 2160
IPD: 0.064
Convergence: 0.0
Display Mode: Half-SBS
Model List:
  Depth-Anything-V2-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Video-Depth-Anything-Small:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Video-Depth-Anything-Base:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Video-Depth-Anything-Large:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  DA3-SMALL:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3-BASE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3-LARGE-1.1:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3-GIANT-1.1:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3NESTED-GIANT-LARGE-1.1:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3MONO-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  DA3METRIC-LARGE:
    resolutions:
    - 182
    - 224
    - 280
    - 322
    - 378
    - 434
    - 504
  Depth-Anything-V2-Metric-Outdoor-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Metric-Outdoor-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Metric-Outdoor-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Metric-Indoor-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Metric-Indoor-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Depth-Anything-V2-Metric-Indoor-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Metric-Video-Depth-Anything-Small:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Metric-Video-Depth-Anything-Base:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Metric-Video-Depth-Anything-Large:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything-small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything-base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-anything-large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Distill-Any-Depth-Small-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Distill-Any-Depth-Base-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  Distill-Any-Depth-Large-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-small-kitti:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-base-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-large-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-giant-kitti-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-small-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-base-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-large-nyu-hf:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  dpt-dinov2-giant-nyu:
    resolutions:
    - 196
    - 238
    - 294
    - 336
    - 392
    - 448
    - 518
  depth-ai-hf:
    resolutions:
    - 192
    - 224
  dpt-hybrid-midas-hf:
    resolutions:
    - 384
  dpt-beit-base-384:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  dpt-beit-large-512:
    resolutions:
    - 192
    - 288
    - 384
    - 448
    - 512
  dpt-large:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  dpt-large-redesign-hf:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  zoedepth-nyu-kitti:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  zoedepth-nyu:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  zoedepth-kitti:
    resolutions:
    - 192
    - 240
    - 288
    - 336
    - 384
  DepthPro-hf:
    resolutions:
    - 1536
Depth Model: DA3-SMALL
Depth Strength: 2.0
Anti-aliasing: 2
Foreground Scale: 0.5
Depth Resolution: 322
FP16: false
Download Path: models
HF Endpoint: https://hf-mirror.com
Computing Device: 0
Language: CN
Run Mode: Local Viewer
Stream Protocol: HLS
Streamer Port: 1122
Stream Quality: 100
torch.compile: true
TensorRT: true
Recompile TensorRT: false
CoreML: false
Recompile CoreML: false
OpenVINO: false
Recompile OpenVINO: false
Capture Tool: DesktopDuplication
Fill 16:9: true
Fix Viewer Aspect: false
Lossless Scaling Support: false
Stream Key: live
Stereo Mix: ''
CRF: 20
Audio Delay: -0.15
Specify Display: false
Stereo Monitor: 1
