#!/bin/bash
cd "$(dirname "$0")"
# Set variables
REPO_OWNER="lc700x"
REPO_NAME="desktop2stereo"
BRANCH="update"
ZIP_FILE="${REPO_NAME}-${BRANCH}.zip"
DOWNLOAD_URL="https://github.com/${REPO_OWNER}/${REPO_NAME}/archive/refs/heads/${BRANCH}.zip"

# Download the ZIP archive
echo "Downloading branch '${BRANCH}'..."
curl -L -o "$ZIP_FILE" "$DOWNLOAD_URL"

# Extract to temp folder
echo "Extracting files..."
unzip -q "$ZIP_FILE" -d temp_extract

# Move contents from nested folder to current directory
mv temp_extract/${REPO_NAME}-${BRANCH}/* ./

# Clean up
rm -rf temp_extract "$ZIP_FILE"
# cleanup windows rtmp folders
rm -rf ./rtmp/ffmpeg
rm -rf ./rtmp/mediamtx

echo "Branch '${BRANCH}' downloaded and extracted to current folder."
# Install requirements
echo
echo "- Installing the requirements"
$PYTHON_EXE -m pip install -r requirements.txt --no-cache-dir --trusted-host http://mirrors.aliyun.com/pypi/simple/
if [ $? -ne 0 ]; then
    echo "Failed to install requirements"
    read -p "Press enter to exit..."
    exit 1
fi

echo "Python environment deployed successfully."
read -p "Press enter to exit..."
exit 0

